name: Test

on: [ push, pull_request ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: typst-community/setup-typst@v4
      - uses: actions/checkout@v4
      - name: Extract version
        run: |
          VERSION=$(awk -F'= *' '/^version/{gsub(/"/,"",$2);print $2}' typst.toml)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: Link local template package
        run: |
          mkdir -p ~/.local/share/typst/packages/preview/accelerated-jacow
          ln -s $(pwd) ~/.local/share/typst/packages/preview/accelerated-jacow/$VERSION
      - name: Install font
        run: |
          sudo apt install tex-gyre
      - name: Init & compile
        run: |
          typst init @preview/accelerated-jacow:$VERSION
          cd accelerated-jacow
          ls -l
          grep "#import \"@preview/accelerated-jacow:$VERSION\"" *.typ
          typst compile *.typ
          ls -l
      - uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: 'accelerated-jacow/*.pdf'
          if-no-files-found: error
